name: Proxy Checker

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run proxy checker
        run: node check.js

      - name: Commit & Push result (reset history)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan latest_branch
          git add proxies.txt
          git commit -m "update alive proxies"
          git branch -D main
          git branch -m main
          git push -f origin main
